-- autogenerated = 1
-- converted to Lua for Hyprland 0.55+

-----------------
--- MONITORS ---
-----------------
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })
hl.monitor({ output = "eDP-1", mode = "preferred", position = "auto", scale = "2" })

-------------------
--- MY PROGRAMS ---
-------------------
local terminal = "kitty"
local fileManager = "nautilus"
local menu = "wofi --show drun"
local mainMod = "SUPER"

-----------------
--- AUTOSTART ---
-----------------
hl.on("hyprland.start", function()
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("waybar & swaync & hypridle")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("~/.config/hypr/wallpaper.sh")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("kitty", { workspace = "5 silent" })
    hl.exec_cmd("firefox", { workspace = "4 silent" })
    hl.exec_cmd("zen", { workspace = "2 silent" })
    hl.exec_cmd("fcitx5 -d")
end)

-----------------------------
--- ENVIRONMENT VARIABLES ---
-----------------------------
hl.env("XMODIFIERS", "@im=fcitx")
hl.env("QT_IM_MODULE", "fcitx")
hl.env("SDL_IM_MODULE", "fcitx")
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

---------------------
--- LOOK AND FEEL ---
---------------------
hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 20,
        border_size = 2,
        col = {
            active_border = { colors = { "rgba(ff69b4ee)", "rgba(ff1493ee)" }, angle = 45 },
            inactive_border = "rgba(ff69b444)",
        },
        resize_on_border = false,
        allow_tearing = false,
        layout = "dwindle",
    },

    decoration = {
        rounding = 10,
        rounding_power = 2,
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        blur = {
            enabled = true,
            size = 9,
            passes = 2,
            vibrancy = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },

    dwindle = {
        preserve_split = true,
    },

    master = {
        new_status = "master",
    },

    misc = {
        force_default_wallpaper = -1,
        disable_hyprland_logo = false,
    },

    input = {
        kb_layout = "us",
        kb_variant = "",
        kb_model = "",
        kb_options = "caps:ctrl_shifted_capslock",
        kb_rules = "",
        follow_mouse = 1,
        sensitivity = 0,
        touchpad = {
            natural_scroll = true,
        },
    },
})

-----------------
--- DEVICES ---
-----------------
hl.device({
    name = "epic-mouse-v1",
    sensitivity = -1.0,
})

------------------
--- ANIMATIONS ---
------------------
hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })

hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows", enabled = true, speed = 4.79, bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.1, bezier = "easeOutQuint", style = "popin 87%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.49, bezier = "linear", style = "popin 87%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade", enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers", enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 4, bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 1.5, bezier = "linear", style = "fade" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor", enabled = true, speed = 7, bezier = "quick" })

------------------
--- WINDOW RULES & LAYER RULES ---
------------------
hl.layer_rule({ match = "namespace:^wofi$", blur = 1 })
hl.layer_rule({ match = "namespace:^wofi$", ignore_alpha = 0 })
hl.layer_rule({ match = "namespace:^rofi$", blur = 1 })
hl.layer_rule({ match = "namespace:^rofi$", ignore_alpha = 0 })

hl.window_rule({ match = { class = "^wofi$" }, animation = "slide" })
hl.window_rule({ match = { class = "^wofi$" }, dim_around = "1.0" })
hl.window_rule({ match = { class = "^rofi$" }, animation = "slide" })
hl.window_rule({ match = { class = "^rofi$" }, dim_around = "1.0" })

hl.window_rule({ match = { class = "^kitty$" }, workspace = "5" })
hl.window_rule({ match = { class = "^kitty$" }, opacity = "0.75 0.75 0.75" })
hl.window_rule({ match = { class = "^firefox$" }, workspace = "4" })
hl.window_rule({ match = { class = "^firefox$" }, opacity = "0.85 0.85 0.85" })
hl.window_rule({ match = { class = "^firefox$", title = ".*YouTube.*" }, opacity = "1.0 1.0 1.0 override" })
hl.window_rule({ match = { class = "^blueman-manager$" }, opacity = "0.75 0.75 0.75" })
hl.window_rule({ match = { class = "^zen$" }, opacity = "0.85 0.85 0.85" })

-------------------
--- KEYBINDINGS ---
-------------------
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("pkill wofi || cliphist list | wofi --dmenu | cliphist decode | wl-copy"))
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + BackSpace", hl.dsp.window.close())
hl.bind(mainMod .. " + M", hl.dsp.exit())
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + F", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + Space", hl.dsp.exec_cmd("pkill wofi || " .. menu))
hl.bind("ALT + Space", hl.dsp.exec_cmd("pgrep rofi || rofi -show drun"))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind("F11", hl.dsp.window.fullscreen())
hl.bind("ALT + Return", hl.dsp.window.fullscreen())
hl.bind("SUPER + A", hl.dsp.exec_cmd("~/.config/hypr/rand.sh"))
hl.bind(mainMod .. " + K", hl.dsp.exec_cmd("pkill -9 quickshell || quickshell"))

hl.bind("Print", hl.dsp.exec_cmd("hyprshot -m window -o ~/Pictures/Screenshots"))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd("hyprshot -m region -o ~/Pictures/Screenshots"))
hl.bind("SUPER + X", hl.dsp.exec_cmd("hyprlock"))
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("~/.local/bin/screen-recorder toggle"))
hl.bind(mainMod .. " + ALT + R", hl.dsp.exec_cmd("~/.local/bin/screen-recorder pause"))

-- Protect Workspace 4 from being recorded (Hyprland Censor Box)
hl.window_rule({ match = { workspace = "4" }, no_screen_share = true })

hl.bind("ALT + W", hl.dsp.exec_cmd("~/.config/system_scripts/wifi-menu.sh"))
hl.bind("ALT + Q", hl.dsp.exec_cmd("blueman-manager"))
hl.bind("ALT + E", hl.dsp.exec_cmd("pavucontrol -t 3"))
hl.bind(mainMod .. " + G", hl.dsp.exec_cmd("~/.config/hypr/toggle_wallpaper.sh"))

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" }))
hl.bind("ALT + Tab", hl.dsp.window.cycle_next())

-- Switch workspaces
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = "1" }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = "2" }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = "3" }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = "4" }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = "5" }))
hl.bind(mainMod .. " + D", hl.dsp.window.fullscreen({ type = 0 }))

-- Move active window to a workspace
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = "1" }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = "2" }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = "3" }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = "4" }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = "5" }))

-- Special workspace
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through workspaces
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e+1" }))

-- Move/resize with mouse
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Media & Brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"),
    { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),
    { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),
    { locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),
    { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })

-- Playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-- Trackpad Gestures
hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Resize Windows (binde equivalent)
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.window.resize({ x = 10, y = 0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + H", hl.dsp.window.resize({ x = -10, y = 0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.window.resize({ x = 0, y = -10, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + J", hl.dsp.window.resize({ x = 0, y = 10, relative = true }), { repeating = true })


local floating_classes = { "^qemu$", "^swayimg$", "blueman-manager", "org.pulseaudio.pavucontrol" }
for _, class_name in ipairs(floating_classes) do
    hl.window_rule({
        name = "float-" .. class_name,
        match = { class = class_name },
        float = true,
        center = true,
    })
end
