# BACKGROUND
background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    no_fade_in = false
    no_fade_out = false
    hide_cursor = true
    grace = 0
    disable_loading_bar = true
    ignore_empty_input = true
}

# INPUT FIELD
input-field {
    monitor =
    # SIZE CHANGED: Much wider (1000px) and slightly taller (70px)
    size = 1000, 70
    outline_thickness = 2
    
    dots_size = 0.5
    dots_spacing = 0.3
    dots_center = true
    
    outer_color = rgba(137, 180, 250, 0.5) 
    inner_color = rgba(30, 30, 46, 0.5) 
    font_color = rgb(205, 214, 244)
    check_color = rgb(250, 179, 135)
    fail_color = rgb(243, 139, 168)

    fade_on_empty = false
    placeholder_text = <b><span foreground="##a6adc8">Input Password..</span></b>
    
    hide_input = false
    rounding = -1
    
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 300
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1

    # POSITION: bottom center
    position = 0, 100
    halign = center
    valign = bottom
}

# FINGERPRINT LABEL
label {
    monitor =
    text =   Scan Fingerprint 
    color = rgba(205, 214, 244, 0.7)
    font_size = 18
    font_family = JetBrains Mono Nerd Font
    
    # Input field is at 100px from bottom.
    position = 0, 200
    halign = center
    valign = bottom
}

# TIME
label {
  monitor = 
  text = cmd[update:1000] date +"%-I:%M"
  color = rgb(205, 214, 244)
  # SIZE CHANGED: Huge clock
  font_size = 200
  font_family = JetBrains Mono Extrabold
  # POSITION CHANGED: Dead center of screen
  position = 0, 150
  halign = center
  valign = center
}

label {
    monitor =
    # 2>/dev/null hides errors if nothing is playing so the screen stays clean
    text = cmd[update:1000] echo "$(playerctl metadata --format '{{title}}    {{artist}}' 2>/dev/null)"
    color = rgba(205, 214, 244, 1.0)
    font_size = 18
    font_family = JetBrains Mono Nerd Font
    position = 0, 50
    halign = center
    valign = bottom
}

# DATE
label {
  monitor =
  text = cmd[update:1000] date +"%A, %B %d"
  color = rgb(205, 214, 244)
  font_size = 25
  font_family = JetBrains Mono
  # POSITION CHANGED: Just below the clock
  position = 0, 0
  halign = center
  valign = center
}

auth {
    fingerprint:enabled = true
    fingerprint:ready_message = Scan fingerprint to unlock
    fingerprint:present_message = Scanning fingerprint...
}
